INSERT INTO public.equipos(id,
             cod_equipo, nom_equipo, activo_equipo, fecha_creacion, created_at,
            updated_at, porcentaje)
    VALUES (1,1, 'Rusia', TRUE , current_date, current_date,current_date, 50.70),
    (2,2, 'Egipto', TRUE , current_date, current_date,current_date,46.10),
    (3,3, 'Arabia Saudita',TRUE ,current_date, current_date,current_date, 43.90),
    (4,4, 'Uruguay', TRUE, current_date, current_date,current_date,59.20),
    (5,5, 'Portugal', TRUE, current_date, current_date,current_date,55.60),
    (6,6, 'Espa�a',TRUE ,current_date, current_date,current_date, 73.60),
    (7,7, 'Ir�n',TRUE ,current_date, current_date,current_date,41.30),
    (8,8, 'Marruecos', TRUE , current_date, current_date,current_date,29.50),
    (9,9, 'Francia', TRUE, current_date, current_date,current_date,75.80),
    (10,10, 'Per�', TRUE, current_date, current_date,current_date,42.60),
    (11,11, 'Dinamarca', TRUE, current_date, current_date,current_date,39.60),
    (12,12, 'Australia',TRUE , current_date, current_date,current_date,42.00),
    (13,13, 'Argentina', TRUE, current_date, current_date,current_date,75.60),
    (14,14, 'Croacia',TRUE ,current_date, current_date,current_date,45.20),
    (15,15, 'Islandia', TRUE,current_date, current_date,current_date,38.50 ),
    (16,16, 'Nigeria',TRUE ,current_date, current_date,current_date,40.60),
    (17,17, 'Brasil', TRUE, current_date, current_date,current_date,80.20),
    (18,18, 'Costa Rica', TRUE,current_date, current_date,current_date,36.60),
    (19,19, 'Suiza', TRUE, current_date, current_date,current_date,40.20),
    (20,20, 'Serbia', TRUE, current_date, current_date,current_date,43.00),
    (21,21, 'Alemania',TRUE , current_date, current_date,current_date,76.10),
    (22,22, 'M�xico',TRUE , current_date, current_date,current_date,43.70),
    (23,23, 'Corea del Sur', TRUE, current_date, current_date,current_date,36.30),
    (24,24,'Suecia', TRUE, current_date, current_date,current_date,43.90),
    (25,25, 'Belgica', TRUE, current_date, current_date,current_date,65.40),
    (26,26, 'Inglaterra', TRUE, current_date, current_date,current_date,53.90),
    (27,27, 'Panam�',TRUE ,current_date, current_date,current_date, 39.50),
    (28,28, 'T�nez', TRUE,current_date, current_date,current_date, 41.20),
    (29,29, 'Polonia',TRUE ,current_date, current_date,current_date,47.50),
    (30,30, 'Colombia', TRUE, current_date, current_date,current_date,55.20),
    (31,31, 'Jap�n', TRUE, current_date, current_date,current_date,51.80),
    (32,32, 'Senegal',TRUE , current_date, current_date,current_date,45.60);